name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1  # Replace with your AWS region

      - name: Set up SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa  # GitHub secret for SSH private key
          chmod 600 ~/.ssh/id_rsa  # Make it secure

      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts  # Ensure EC2's SSH fingerprint is known

      # Wait for EC2 to be ready (Optional, if you expect delays)
      - name: Wait for EC2 to be ready
        run: |
          while ! nc -zv ${{ secrets.EC2_HOST }} 22; do
            echo "Waiting for EC2 to be ready..."
            sleep 10
          done

      - name: Run deploy script on EC2
        run: |
          EC2_IP="${{ secrets.EC2_HOST }}"  # Public IP or DNS of your EC2
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$EC2_IP 'bash -s' < ./deploy.sh
